### ISSUE TITLE
Installation bricht ab

### ISSUE THREAD

**Issue by kubjo** [terminal42/contao-rte_table#1]
Hi, ich wollte es eben unter 4.5.6 via console und composer instalieren, leider bricht die Installation mit der Fehlermeldung: "The module folder "system/modules/_autoload" does not exist." ab.  
Habe ich eine zu hohe Version von contao? Kann man das was machen?

**Comment by aschempp** [comment]
The autoload.ini contains a hardcoded dependency on our `NamespaceClassLoader`, which is not necessary for Composer installation. Should be an optional dependency.
