### ISSUE TITLE
500 Internal Server Error after Update to 4.9.28

### ISSUE THREAD

**Issue by simon-1977** [terminal42/contao-rte_table#10]
After the update to 4.9.28, i have an error message: "500 Internal Server Error".

The webserver log says:

> Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'DC_Contao\\DC_Table' not found in /var/www/html/xxx/htdocs/vendor/terminal42/contao-rte_table/src/RteEditor.php:73\nStack trace:\n#0 /var/www/html/xxx/htdocs/vendor/terminal42/contao-rte_table/public/wizard.php(34): Terminal42\\RteTable\\RteEditor->run()\n#1 {main}\n  thrown in /var/www/html/xxx/htdocs/vendor/terminal42/contao-rte_table/src/RteEditor.php on line 73'

**Comment by swinde** [comment]
Frage, könnte das evtl. mit dieser Änderung in C 4.9.28 zusammen hängen? Mit Contao Versionen <=4.9.27 funktioniert die Funktion des Modules noch. https://github.com/contao/contao/pull/4285

**Comment by Samson1964** [comment]
Bekomme denselben Fehler.

**Comment by johannes-bittner** [comment]
Dito

**Comment by xprojects-de** [comment]
Dito
