### ISSUE TITLE
order of cancel and save buttons (german)

### ISSUE THREAD

**Issue by vicotec** [terminal42/contao-rte_table#13]
It is very irritating to me that (at least in german), the order of the cancel and save button for the tinyMCE popup is the exact reverse to all other contao elements. This has me constantly accidentally closing the popup without saving.

My suggestion would be to switch the order of the buttons to be consistent with the rest of contao, or provide a warning dialog upon clicking cancel.

**Comment by aschempp** [comment]
Fixed in Version 2.0.0 for Contao 5.3+
