### ISSUE TITLE
eigene TinyMCE Konfiguration nur für Tabellen

### ISSUE THREAD

**Issue by Schmidty2** [terminal42/contao-rte_table#14]
Hallo,
können eigene TinyMCE-Konfigurationen nur für die Tabellen verwendet werden?
Das müste ja theoretisch nach diesem Schema gehen:

// contao/dca/tl_xxxx.php
$GLOBALS['TL_DCA']['tl_xxxx']['fields']['yyyy']['yyyyl']['yyyy'] = 'table_tinyMCE';

Was muss für xxxx bzw. yyyy stehen?
Contao 4.13.13 und PHP 8.1 wird verwendet.
Danke für die Rückmeldung.

**Comment by aschempp** [comment]
Version 2.0.0 for Contao 5.3+ now supports this feature.
