### ISSUE TITLE
contao-rte_table and Contao 5.3 LTS

### ISSUE THREAD

**Issue by sdahlmann** [terminal42/contao-rte_table#16]
Question: Is an adaptation of the Contao extension "contao-rte_table" to Contao 5.x and PHP 8.x planned or possible?

**Comment by Toflar** [comment]
We have no plans to make this extension compatible at the moment because we don't need it ourselves. Feel free to get in touch if you do and you're interested in changing this situation :)

**Comment by minstyle** [comment]
@Toflar It would be nice if you make this extension compatible for Contao 5 and PHP 8 👌

**Comment by aschempp** [comment]
> We have no plans to make this extension compatible at the moment because we don't need it ourselves.

That situation has changed 🙃 Version 2.0.0 now supports Contao 5.3. Feel free to donate (https://github.com/sponsors/terminal42 or https://ko-fi.com/terminal42) if you rely on this extension 😉
