### ISSUE TITLE
"Edit content" Fenster bleibt leer. 

### ISSUE THREAD

**Issue by kubjo** [terminal42/contao-rte_table#2]
Ich konnte jetzt die Erweiterung ohne Probleme via composer installieren, die Tabelle wird im BE jetzt auch größer dargestellt. Beim hoovern erscheint "Edit content" beim Klick darauf wird ein Popup geöffnet, das die Überschrift "Edit content" enthält, aber sonst leer ist. Die Schaltflächen "Edit" und "Schließen" erscheinen erst mal schwarz, werden nach ca. 1 Sekunde ausgegraut. Der TinyMCE ist bei anderen CE in Ordnung!

Grüße aus Ludwigsburg
Jochen Kubik

**Comment by fritzmg** [comment]
Vermutlich muss noch die [wizard.php](https://github.com/terminal42/contao-rte_table/blob/master/public/wizard.php) angepasst werden. Also zB.:
```diff
<?php

/**
 * rte_table extension for Contao Open Source CMS
 *
 * @copyright  Copyright (c) 2008-2016, terminal42 gmbh
 * @author     terminal42 gmbh <info@terminal42.ch>
 * @license    http://opensource.org/licenses/lgpl-3.0.html LGPL
 * @link       http://github.com/terminal42/rte_table
 */

// Set the script name
define('TL_SCRIPT', 'system/modules/rte_table/public/wizard.php');

// Initialize the system
define('TL_MODE', 'BE');
-require dirname(__DIR__) . '/../../../system/initialize.php';
+if (file_exists('../../../initialize.php')) {
+    // Regular way
+    /** @noinspection PhpIncludeInspection */
+    require_once '../../../initialize.php';
+} elseif (file_exists('../../../../system/initialize.php')) {
+    // Contao 4 - Try composer location
+    /** @noinspection PhpIncludeInspection */
+    require_once '../../../../system/initialize.php';
+} else {
+    // Contao 3 - Try composer location
+    /** @noinspection PhpIncludeInspection */
+    require_once '../../../../../system/initialize.php';
+}

// Run the controller
$controller = new \Terminal42\RteTable\RteEditor;
$controller->run();
```
Teste mal diese Änderung.

**Comment by kubjo** [comment]
Führt leider zum selben Ergebnis.

**Comment by qzminski** [comment]
I was able to reproduce and fix the issue (thanks @fritzmg). @kubjo please update the extension to 1.0.2  which will be released today and if that still does not work for you, please provide the error log (usually located in `/system/logs/error.log`).

**Comment by kubjo** [comment]
Everthing ist working fine so far! 
@fritzmg , @qzminski , @Toflar , @aschempp 
Thanx for your support!
