### ISSUE TITLE
Additional Line Breaks

### ISSUE THREAD

**Issue by 9teufel** [terminal42/contao-rte_table#3]
After each line a br is added. The line breaks are not shown in Tiny, only in frontend output.

See the examples:

Example 1:
Input Tiny:

```
<p>first paragraph</p>
<p>second paragraph</p>
```

Output:
```
<p>first paragraph</p><br>
<p>second paragraph</p>
```

Example 2:
Input Tiny:

```
<p>paragraph</p>
<ul>
<li>entry</li>
<li>entry</li>
<li>entry</li>
</ul>
```

Output:
```
<p>paragraph</p><br>
<ul><br>
<li>entry</li><br>
<li>entry</li><br>
<li>entry</li><br>
</ul>
```

**Comment by V15** [comment]
It's not a contao-rte_table problem it's because of Contao.
[https://github.com/contao/contao/issues/159](https://github.com/contao/contao/issues/159)
