### ISSUE TITLE
Not possible to link to a File: Internal Server Error - The table name must not be empty

### ISSUE THREAD

**Issue by V15** [terminal42/contao-rte_table#4]
If I try to link some content in a table cell to a file (pdf for example) I get an error:

Internal Server Error
Was ist das Problem?
The table name must not be empty

**How to reproduce?**

- Open a table element
- Hover over any table cell -> Edit content
- The Window "Edit content" opens
- Mark a word or sentence
- Click Button: Insert Link
- The Window "Insert Link" opens
- Field URL: Click on the "Search for file" button

-> The Error "Internal Server Error - The table name must not be empty" is shown

**Comment by qzminski** [comment]
Fixed in version 1.0.3 which has been just released.
