### ISSUE TITLE
Overlay optional abschaltbar?

### ISSUE THREAD

**Issue by Samson1964** [terminal42/contao-rte_table#9]
Ich habe gerade die Erweiterung installiert, weil ein Redakteur keine Lust hatte mit HTML-Code und Inserttags in den ganzen Zellen zu arbeiten. Nun habe ich zwei Probleme:

1. Die Erweiterung sollte im Inhaltselement oder global (Benutzerprofil) abschaltbar sein, damit man die Zellen direkt bearbeiten kann wie unter Contao üblich.
2. Der TinyMCE erzeugt p-Tags, die in Tabellenzellen stören. Als Lösung habe ich per CSS margin und padding für p-Tags dort auf 0 gesetzt.

**Comment by aschempp** [comment]
der tinyMCE lässt sich pro Benutzer deaktivieren. Dass P-Tags generiert werden ist das Prinzip von TinyMCE, darauf hat die Erweiterung keinen Einfluss.
